### PR TITLE
Add GitHub repository URL config for "Fork me on GitHub" ribbon

### PR DESCRIPTION
**Pull request by daffl**
Great job! I used Paige for my latest project and already got great feedback.  Someone also suggested to make the GitHub repository URL more prominent, which I found a good idea.

I added a configuration option where you can set your GitHub repository URL. If set, it will show the famous "Fork me on GitHub" ribbon on the main page. Thought that would make sense for a GitHub page generator.

Daff

### CODE REVIEW

**Comment by rthauby** [comment]
Hey, nice work on this. I'll be pushing a new version with a few minor tweaks (including this one) to npm today. Thanks for the feature!

**Comment by daffl** [comment]
Awesome, thanks for merging. And the page has been updated too, cool. Just noticed that my tabs are messed up. Hope that is not too big of a deal, I can fix it if need be.

**Comment by rthauby** [comment]
no problem!

Which tabs? for the page index? They look ok to me.

**Comment by daffl** [comment]
You're right, I think you can only see it in the configuration file example. Don't think its a big deal, I will remember it next time. Thanks again for putting it all up, now I can use the NPM version again :)

**Pull request merged**
